[[redirects]]
  from = "/api/*"
  to = "https://lakku-lakku.com/api/v1/:splat"
  status = 200
  
[[redirects]]
  from = “/*”
  to = “/index.html”
  status = 200
  
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
