[[redirects]]
  from = "/*"
  to = "https://lakku-lakku.com/api/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
